/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import modelo.TextPrompt;

/**
 *
 * @author judag
 */
public class frmIngresarMedicamento extends javax.swing.JFrame {

    /** Creates new form frmIngresarMedicamento */
    public frmIngresarMedicamento() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt placeHolderCodigo = new TextPrompt("Codigo", txtCodigo);        
        TextPrompt placeHolderCodigoBarra = new TextPrompt("Codigo Barra", txtCodigoBarra);  
        TextPrompt placeHolderNombreComercial = new TextPrompt("Nombre Comercial", txtNombreComercial);  
        TextPrompt placeHolderInventarioMin = new TextPrompt("Inventario Minimo", txtInventarioMin);  
        TextPrompt placeHolderPrecioCompra = new TextPrompt("Precio Compra", txtPrecioCompra);
        TextPrompt placeHolderPrecioVenta = new TextPrompt("Precio Venta", txtPrecioVenta);
        
        
        
        TextPrompt placeHolderNombreGenerico = new TextPrompt("Nombre Generico", txtNombreGenerico);
        TextPrompt placeHolderConcentracion = new TextPrompt("Concentracion", txtConcentracion);
        TextPrompt placeHolderComposicion = new TextPrompt("Composicion", txtComposicion);
        TextPrompt placeHolderRegistroSanitario = new TextPrompt("Registro Sanitario", txtRegistroSanitario);
        TextPrompt placeHolderAdvertencia = new TextPrompt("Advertencia", txtAdvertencia);
        TextPrompt placeHolderLeyenda = new TextPrompt("Leyenda", txtLeyenda);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMedicamento = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        txtNombreComercial = new javax.swing.JTextField();
        txtInventarioMin = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        cbxActivo = new javax.swing.JComboBox<>();
        btnEnfermedad = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtpFechaCreacion = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        lblCaracteristicasMedicamento = new javax.swing.JLabel();
        txtNombreGenerico = new javax.swing.JTextField();
        txtConcentracion = new javax.swing.JTextField();
        txtComposicion = new javax.swing.JTextField();
        txtRegistroSanitario = new javax.swing.JTextField();
        txtAdvertencia = new javax.swing.JTextField();
        txtLeyenda = new javax.swing.JTextField();
        btnFabricante = new javax.swing.JButton();
        btnCondicion = new javax.swing.JButton();
        btnFormaFarmaceutica = new javax.swing.JButton();
        btnViaAdministracion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dtpFechaExpiracion = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IngresarMedicamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 249, 249));
        jPanel2.setLayout(new java.awt.GridLayout(9, 1, 0, 5));

        lblMedicamento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicamento.setText("Medicamento");
        jPanel2.add(lblMedicamento);

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtCodigo);

        txtCodigoBarra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigoBarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtCodigoBarra);

        txtNombreComercial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreComercial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtNombreComercial);

        txtInventarioMin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtInventarioMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtInventarioMin);

        txtPrecioCompra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPrecioCompra);

        txtPrecioVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecioVenta);

        cbxActivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbxActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActivoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxActivo);

        btnEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEnfermedad.setText("Enfermedad");
        jPanel2.add(btnEnfermedad);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Fecha creacion");
        jPanel5.add(jLabel1);

        dtpFechaCreacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel5.add(dtpFechaCreacion);

        jPanel4.setBackground(new java.awt.Color(255, 249, 249));
        jPanel4.setLayout(new java.awt.GridLayout(11, 1, 0, 5));

        lblCaracteristicasMedicamento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCaracteristicasMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaracteristicasMedicamento.setText("Caracteristicas Medicamento");
        jPanel4.add(lblCaracteristicasMedicamento);

        txtNombreGenerico.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreGenerico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtNombreGenerico);

        txtConcentracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtConcentracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtConcentracion);

        txtComposicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtComposicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtComposicion);

        txtRegistroSanitario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRegistroSanitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtRegistroSanitario);

        txtAdvertencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAdvertencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtAdvertencia);

        txtLeyenda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLeyenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtLeyenda);

        btnFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFabricante.setText("Fabricante");
        jPanel4.add(btnFabricante);

        btnCondicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCondicion.setText("Condicion de Almacenamiento");
        jPanel4.add(btnCondicion);

        btnFormaFarmaceutica.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFormaFarmaceutica.setText("Forma Farmaceutica");
        jPanel4.add(btnFormaFarmaceutica);

        btnViaAdministracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnViaAdministracion.setText("Via de Administracion");
        jPanel4.add(btnViaAdministracion);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Fecha expiracion");
        jPanel6.add(jLabel2);

        dtpFechaExpiracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel6.add(dtpFechaExpiracion);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        jPanel3.add(btnAceptar);

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel3.add(btnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void cbxActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActivoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCondicion;
    public javax.swing.JButton btnEnfermedad;
    public javax.swing.JButton btnFabricante;
    public javax.swing.JButton btnFormaFarmaceutica;
    public javax.swing.JButton btnViaAdministracion;
    public javax.swing.JComboBox<String> cbxActivo;
    private com.toedter.calendar.JDateChooser dtpFechaCreacion;
    private com.toedter.calendar.JDateChooser dtpFechaExpiracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCaracteristicasMedicamento;
    private javax.swing.JLabel lblMedicamento;
    public javax.swing.JTextField txtAdvertencia;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtCodigoBarra;
    public javax.swing.JTextField txtComposicion;
    public javax.swing.JTextField txtConcentracion;
    public javax.swing.JTextField txtInventarioMin;
    public javax.swing.JTextField txtLeyenda;
    public javax.swing.JTextField txtNombreComercial;
    public javax.swing.JTextField txtNombreGenerico;
    public javax.swing.JTextField txtPrecioCompra;
    public javax.swing.JTextField txtPrecioVenta;
    public javax.swing.JTextField txtRegistroSanitario;
    // End of variables declaration//GEN-END:variables

}
