/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import modelo.TextPrompt;

/**
 *
 * @author judag
 */
public class frmIngresarMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresarMedicamentoTest
     */
    public frmIngresarMedicamento() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt placeHolderCodigo = new TextPrompt("Codigo", txtCodigo);
        TextPrompt placeHolderCodigoBarra = new TextPrompt("Codigo Barra", txtCodigoBarra);
        TextPrompt placeHolderNombreComercial = new TextPrompt("Nombre Comercial", txtNombreComercial);
        TextPrompt placeHolderInventarioMin = new TextPrompt("Inventario Minimo", txtInventarioMin);
        TextPrompt placeHolderPrecioCompra = new TextPrompt("Precio Compra", txtPrecioCompra);
        TextPrompt placeHolderPrecioVenta = new TextPrompt("Precio Venta", txtPrecioVenta);

        TextPrompt placeHolderNombreGenerico = new TextPrompt("Nombre Generico", txtNombreGenerico);
        TextPrompt placeHolderConcentracion = new TextPrompt("Concentracion", txtConcentracion);
        TextPrompt placeHolderComposicion = new TextPrompt("Composicion", txtComposicion);
        TextPrompt placeHolderRegistroSanitario = new TextPrompt("Registro Sanitario", txtRegistroSanitario);
        TextPrompt placeHolderAdvertencia = new TextPrompt("Advertencia", txtAdvertencia);
        TextPrompt placeHolderLeyenda = new TextPrompt("Leyenda", txtLeyenda);

        this.jgdEnfermedad.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdFabricante.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdCondicion.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdForma.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdVia.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));

        JTableHeader cabeceraEnfermedad = this.jgdEnfermedad.getTableHeader();
        JTableHeader cabeceraFabricante = this.jgdFabricante.getTableHeader();
        JTableHeader cabeceraCondicion = this.jgdCondicion.getTableHeader();
        JTableHeader cabeceraForma = this.jgdForma.getTableHeader();
        JTableHeader cabeceraVia = this.jgdVia.getTableHeader();

        cabeceraEnfermedad.setOpaque(false);
        cabeceraFabricante.setOpaque(false);
        cabeceraCondicion.setOpaque(false);
        cabeceraForma.setOpaque(false);
        cabeceraVia.setOpaque(false);

        cabeceraEnfermedad.setBackground(new Color(96, 126, 156));
        cabeceraFabricante.setBackground(new Color(96, 126, 156));
        cabeceraCondicion.setBackground(new Color(96, 126, 156));
        cabeceraForma.setBackground(new Color(96, 126, 156));
        cabeceraVia.setBackground(new Color(96, 126, 156));

        cabeceraEnfermedad.setForeground(Color.white);
        cabeceraFabricante.setForeground(Color.white);
        cabeceraCondicion.setForeground(Color.white);
        cabeceraForma.setForeground(Color.white);
        cabeceraVia.setForeground(Color.white);

        cabeceraEnfermedad.setReorderingAllowed(false);
        cabeceraFabricante.setReorderingAllowed(false);
        cabeceraCondicion.setReorderingAllowed(false);
        cabeceraForma.setReorderingAllowed(false);
        cabeceraVia.setReorderingAllowed(false);

        TextPrompt placeHolderBuscarEnfermedad = new TextPrompt("Ingrese su busqueda", txtBuscarEnfermedad);
        TextPrompt placeHolderBuscarFabricante = new TextPrompt("Ingrese su busqueda", txtBuscarFabricante);
        TextPrompt placeHolderBuscarCondicion = new TextPrompt("Ingrese su busqueda", txtBuscarCondicion);
        TextPrompt placeHolderBuscarForma = new TextPrompt("Ingrese su busqueda", txtBuscarForma);
        TextPrompt placeHolderBuscarVia = new TextPrompt("Ingrese su busqueda", txtBuscarVia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMedicamento = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        txtNombreComercial = new javax.swing.JTextField();
        txtInventarioMin = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        cbxActivo = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtpFechaCreacion = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        lblCaracteristicasMedicamento = new javax.swing.JLabel();
        txtNombreGenerico = new javax.swing.JTextField();
        txtConcentracion = new javax.swing.JTextField();
        txtComposicion = new javax.swing.JTextField();
        txtRegistroSanitario = new javax.swing.JTextField();
        txtAdvertencia = new javax.swing.JTextField();
        txtLeyenda = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dtpFechaExpiracion = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtBuscarEnfermedad = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jspEnfermedad = new javax.swing.JScrollPane();
        jgdEnfermedad = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        btnIngresarEnfermedad = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        txtBuscarFabricante = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jspFabricante = new javax.swing.JScrollPane();
        jgdFabricante = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        btnIngresarFabricante = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        txtBuscarCondicion = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jspCondicion = new javax.swing.JScrollPane();
        jgdCondicion = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        btnIngresarCondicion = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        txtBuscarForma = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jspForma = new javax.swing.JScrollPane();
        jgdForma = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        btnIngresarForma = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        txtBuscarVia = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jspVia = new javax.swing.JScrollPane();
        jgdVia = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        btnIngresarVia = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IngresarMedicamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 249, 249));
        jPanel2.setLayout(new java.awt.GridLayout(8, 0));

        lblMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicamento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicamento.setText("Medicamento");
        jPanel2.add(lblMedicamento);

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtCodigo);

        txtCodigoBarra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigoBarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtCodigoBarra);

        txtNombreComercial.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreComercial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtNombreComercial);

        txtInventarioMin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtInventarioMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtInventarioMin);

        txtPrecioCompra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPrecioCompra);

        txtPrecioVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecioVenta);

        cbxActivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbxActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActivoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxActivo);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Fecha creacion");
        jPanel6.add(jLabel1);

        dtpFechaCreacion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel6.add(dtpFechaCreacion);

        jPanel4.setBackground(new java.awt.Color(255, 249, 249));
        jPanel4.setLayout(new java.awt.GridLayout(7, 1));

        lblCaracteristicasMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lblCaracteristicasMedicamento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCaracteristicasMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaracteristicasMedicamento.setText("Caracteristicas Medicamento");
        jPanel4.add(lblCaracteristicasMedicamento);

        txtNombreGenerico.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreGenerico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtNombreGenerico);

        txtConcentracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtConcentracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtConcentracion);

        txtComposicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtComposicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtComposicion);

        txtRegistroSanitario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRegistroSanitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtRegistroSanitario);

        txtAdvertencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAdvertencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtAdvertencia);

        txtLeyenda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLeyenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtLeyenda);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Fecha expiracion");
        jPanel7.add(jLabel2);

        dtpFechaExpiracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(dtpFechaExpiracion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 52, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 52, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(327, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(327, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Medicamento", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarEnfermedad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarEnfermedad)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jspEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdEnfermedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Tipo", "Transmisible", "Mortalidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdEnfermedad.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jgdEnfermedad.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jspEnfermedad.setViewportView(jgdEnfermedad);

        jPanel14.add(jspEnfermedad);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarEnfermedad.setText("Ingresar");
        jPanel15.add(btnIngresarEnfermedad);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Enfermedad", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarFabricante.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarFabricante)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jspFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Razon Social", "Correo", "Pais", "Ciudad", "Direccion", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdFabricante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdFabricante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspFabricante.setViewportView(jgdFabricante);

        jPanel17.add(jspFabricante);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarFabricante.setText("Ingresar");
        jPanel18.add(btnIngresarFabricante);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Fabricante", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarCondicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarCondicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCondicion)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jspCondicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdCondicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdCondicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Humedad", "Temperatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdCondicion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdCondicion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspCondicion.setViewportView(jgdCondicion);

        jPanel20.add(jspCondicion);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarCondicion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarCondicion.setText("Ingresar");
        jPanel21.add(btnIngresarCondicion);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Condicion", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarForma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarForma.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarForma)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarForma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jspForma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdForma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdForma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdForma.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdForma.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspForma.setViewportView(jgdForma);

        jPanel23.add(jspForma);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarForma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarForma.setText("Ingresar");
        jPanel24.add(btnIngresarForma);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Forma", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarVia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarVia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarVia)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarVia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jspVia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdVia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdVia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdVia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdVia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspVia.setViewportView(jgdVia);

        jPanel26.add(jspVia);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarVia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarVia.setText("Ingresar");
        jPanel27.add(btnIngresarVia);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Via", jPanel12);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        jPanel5.add(btnAceptar);

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel5.add(btnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void cbxActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnIngresarCondicion;
    public javax.swing.JButton btnIngresarEnfermedad;
    public javax.swing.JButton btnIngresarFabricante;
    public javax.swing.JButton btnIngresarForma;
    public javax.swing.JButton btnIngresarVia;
    public javax.swing.JComboBox<String> cbxActivo;
    public com.toedter.calendar.JDateChooser dtpFechaCreacion;
    public com.toedter.calendar.JDateChooser dtpFechaExpiracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jgdCondicion;
    public javax.swing.JTable jgdEnfermedad;
    public javax.swing.JTable jgdFabricante;
    public javax.swing.JTable jgdForma;
    public javax.swing.JTable jgdVia;
    public javax.swing.JScrollPane jspCondicion;
    public javax.swing.JScrollPane jspEnfermedad;
    public javax.swing.JScrollPane jspFabricante;
    public javax.swing.JScrollPane jspForma;
    public javax.swing.JScrollPane jspVia;
    private javax.swing.JLabel lblCaracteristicasMedicamento;
    private javax.swing.JLabel lblMedicamento;
    public javax.swing.JTextField txtAdvertencia;
    public javax.swing.JTextField txtBuscarCondicion;
    public javax.swing.JTextField txtBuscarEnfermedad;
    public javax.swing.JTextField txtBuscarFabricante;
    public javax.swing.JTextField txtBuscarForma;
    public javax.swing.JTextField txtBuscarVia;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtCodigoBarra;
    public javax.swing.JTextField txtComposicion;
    public javax.swing.JTextField txtConcentracion;
    public javax.swing.JTextField txtInventarioMin;
    public javax.swing.JTextField txtLeyenda;
    public javax.swing.JTextField txtNombreComercial;
    public javax.swing.JTextField txtNombreGenerico;
    public javax.swing.JTextField txtPrecioCompra;
    public javax.swing.JTextField txtPrecioVenta;
    public javax.swing.JTextField txtRegistroSanitario;
    // End of variables declaration//GEN-END:variables
}
