/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import modelo.TextPrompt;

/**
 *
 * @author judag
 */
public class frmIngresarInventario extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresarTransaccion
     */
    public frmIngresarInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jgdPaciente.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdProveedor.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));
        this.jgdTransaccion.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 14));

        JTableHeader cabeceraPaciente = this.jgdPaciente.getTableHeader();
        JTableHeader cabeceraProveedor = this.jgdProveedor.getTableHeader();
        JTableHeader cabeceraTransaccion = this.jgdTransaccion.getTableHeader();

        cabeceraPaciente.setOpaque(false);
        cabeceraPaciente.setBackground(new Color(96, 126, 156));
        cabeceraPaciente.setForeground(Color.white);
        cabeceraPaciente.setReorderingAllowed(false);
        TextPrompt placeHolderBuscarPaciente = new TextPrompt("Ingrese su busqueda", txtBuscarPaciente);

        cabeceraProveedor.setOpaque(false);
        cabeceraProveedor.setBackground(new Color(96, 126, 156));
        cabeceraProveedor.setForeground(Color.white);
        cabeceraProveedor.setReorderingAllowed(false);
        TextPrompt placeHolderBuscarProveedor = new TextPrompt("Ingrese su busqueda", txtBuscarProveedor);

        cabeceraTransaccion.setOpaque(false);
        cabeceraTransaccion.setBackground(new Color(96, 126, 156));
        cabeceraTransaccion.setForeground(Color.white);
        cabeceraTransaccion.setReorderingAllowed(false);
        TextPrompt placeHolderBuscarTransaccion = new TextPrompt("Ingrese su busqueda", txtBuscarTransaccion);

        this.jtpPanel.setEnabledAt(2, false);
        this.jtpPanel.setEnabledAt(3, false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtpPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        dtpFecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        lblTipoTransaccion = new javax.swing.JLabel();
        cbxTipoTransaccion = new javax.swing.JComboBox<>();
        lblTotalVenta = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtBuscarTransaccion = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jspTransaccion = new javax.swing.JScrollPane();
        jgdTransaccion = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        btnIngresarTransaccion = new javax.swing.JButton();
        btnModificarTransaccion = new javax.swing.JButton();
        btnEliminarTransaccion = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jspProveedor = new javax.swing.JScrollPane();
        jgdProveedor = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        btnIngresarProveedor = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtBuscarPaciente = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jspPaciente = new javax.swing.JScrollPane();
        jgdPaciente = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        btnIngresarPaciente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IngresarInventario");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtpPanel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFecha.setText("Fecha creacion");
        jPanel6.add(lblFecha);

        dtpFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel6.add(dtpFecha);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 0, 5));

        lblTipoTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTipoTransaccion.setText("Tipo de transaccion");
        jPanel2.add(lblTipoTransaccion);

        cbxTipoTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbxTipoTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<>", "Ingreso", "Egreso" }));
        cbxTipoTransaccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoTransaccionItemStateChanged(evt);
            }
        });
        cbxTipoTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoTransaccionActionPerformed(evt);
            }
        });
        jPanel2.add(cbxTipoTransaccion);

        lblTotalVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTotalVenta.setText("Total Venta:");
        jPanel2.add(lblTotalVenta);

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTotalVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtTotalVenta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jtpPanel.addTab("Detalle Transaccion", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarTransaccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarTransaccion)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jspTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdTransaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cantidad", "Medicamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdTransaccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jgdTransaccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspTransaccion.setViewportView(jgdTransaccion);
        if (jgdTransaccion.getColumnModel().getColumnCount() > 0) {
            jgdTransaccion.getColumnModel().getColumn(0).setResizable(false);
            jgdTransaccion.getColumnModel().getColumn(1).setResizable(false);
            jgdTransaccion.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel14.add(jspTransaccion);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarTransaccion.setText("Ingresar");
        jPanel15.add(btnIngresarTransaccion);

        btnModificarTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnModificarTransaccion.setText("Modificar");
        jPanel15.add(btnModificarTransaccion);

        btnEliminarTransaccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEliminarTransaccion.setText("Eliminar");
        jPanel15.add(btnEliminarTransaccion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpPanel.addTab("Transacciones", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarProveedor)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jspProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Razon Social", "Correo", "Direccion", "Telefono", "Representante Legal", "Permiso Operacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdProveedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdProveedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspProveedor.setViewportView(jgdProveedor);

        jPanel7.add(jspProveedor);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarProveedor.setText("Ingresar");
        jPanel11.add(btnIngresarProveedor);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpPanel.addTab("Proveedor", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarPaciente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarPaciente)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jspPaciente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jgdPaciente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jgdPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cedula", "Nombre", "Direccion", "Telefono", "Fecha de Nacimiento", "Nacionalidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jgdPaciente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdPaciente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jgdPaciente.setShowGrid(true);
        jspPaciente.setViewportView(jgdPaciente);

        jPanel16.add(jspPaciente);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresarPaciente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIngresarPaciente.setText("Ingresar");
        jPanel17.add(btnIngresarPaciente);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpPanel.addTab("Paciente", jPanel10);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        jPanel5.add(btnAceptar);

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel5.add(btnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPanel)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtpPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoTransaccionActionPerformed

    private void cbxTipoTransaccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoTransaccionItemStateChanged
        this.jtpPanel.setEnabledAt(2, true);
        this.jtpPanel.setEnabledAt(3, true);

        String item = String.valueOf(this.cbxTipoTransaccion.getSelectedItem());
        if (item.equals("Ingreso")) {
            this.jtpPanel.setEnabledAt(3, false);
        } else if (item.equals("Egreso")) {
            this.jtpPanel.setEnabledAt(2, false);
        } else {
            this.jtpPanel.setEnabledAt(2, false);
            this.jtpPanel.setEnabledAt(3, false);
        }

    }//GEN-LAST:event_cbxTipoTransaccionItemStateChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminarTransaccion;
    public javax.swing.JButton btnIngresarPaciente;
    public javax.swing.JButton btnIngresarProveedor;
    public javax.swing.JButton btnIngresarTransaccion;
    public javax.swing.JButton btnModificarTransaccion;
    public javax.swing.JComboBox<String> cbxTipoTransaccion;
    public com.toedter.calendar.JDateChooser dtpFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTable jgdPaciente;
    public javax.swing.JTable jgdProveedor;
    public javax.swing.JTable jgdTransaccion;
    public javax.swing.JScrollPane jspPaciente;
    public javax.swing.JScrollPane jspProveedor;
    public javax.swing.JScrollPane jspTransaccion;
    public javax.swing.JTabbedPane jtpPanel;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTipoTransaccion;
    private javax.swing.JLabel lblTotalVenta;
    public javax.swing.JTextField txtBuscarPaciente;
    public javax.swing.JTextField txtBuscarProveedor;
    public javax.swing.JTextField txtBuscarTransaccion;
    public javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
