/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Toolkit;

/**
 *
 * @author judag
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("coronavirus.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jmbMenu = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmIngreso = new javax.swing.JMenu();
        jmiReceta = new javax.swing.JMenuItem();
        jmInventario = new javax.swing.JMenu();
        jmiIngreso = new javax.swing.JMenuItem();
        jmiEgreso = new javax.swing.JMenuItem();
        jmiProveedor = new javax.swing.JMenuItem();
        jmMedicamento = new javax.swing.JMenu();
        jmiMedicamento = new javax.swing.JMenuItem();
        jmiEnfermedad = new javax.swing.JMenuItem();
        jmiCondicionAlmacenamiento = new javax.swing.JMenuItem();
        jmiFormaFarmaceutica = new javax.swing.JMenuItem();
        jmiViaAdministracion = new javax.swing.JMenuItem();
        jmiFabricante = new javax.swing.JMenuItem();
        jmReporte = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receta");
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(221, 24, 24));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jmbMenu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmArchivo.setText("Archivo");
        jmArchivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmiAcercaDe.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiAcercaDe.setText("Acerca de");
        jmArchivo.add(jmiAcercaDe);

        jmiSalir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiSalir.setText("Salir");
        jmArchivo.add(jmiSalir);

        jmbMenu.add(jmArchivo);

        jmIngreso.setText("Ingreso");
        jmIngreso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmiReceta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiReceta.setText("Receta");
        jmIngreso.add(jmiReceta);

        jmInventario.setText("Inventario");
        jmInventario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmiIngreso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiIngreso.setText("Ingreso");
        jmiIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresoActionPerformed(evt);
            }
        });
        jmInventario.add(jmiIngreso);

        jmiEgreso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiEgreso.setText("Egreso");
        jmiEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEgresoActionPerformed(evt);
            }
        });
        jmInventario.add(jmiEgreso);

        jmiProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiProveedor.setText("Proveedor");
        jmiProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedorActionPerformed(evt);
            }
        });
        jmInventario.add(jmiProveedor);

        jmIngreso.add(jmInventario);

        jmMedicamento.setText("Medicamento");
        jmMedicamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmiMedicamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiMedicamento.setText("Codificacion");
        jmiMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMedicamentoActionPerformed(evt);
            }
        });
        jmMedicamento.add(jmiMedicamento);

        jmiEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiEnfermedad.setText("Enfermedad");
        jmiEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEnfermedadActionPerformed(evt);
            }
        });
        jmMedicamento.add(jmiEnfermedad);

        jmiCondicionAlmacenamiento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiCondicionAlmacenamiento.setText("Condicion de Almacenamiento");
        jmiCondicionAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCondicionAlmacenamientoActionPerformed(evt);
            }
        });
        jmMedicamento.add(jmiCondicionAlmacenamiento);

        jmiFormaFarmaceutica.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiFormaFarmaceutica.setText("Forma Farmaceutica");
        jmiFormaFarmaceutica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaFarmaceuticaActionPerformed(evt);
            }
        });
        jmMedicamento.add(jmiFormaFarmaceutica);

        jmiViaAdministracion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiViaAdministracion.setText("Via de Administracion");
        jmiViaAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViaAdministracionActionPerformed(evt);
            }
        });
        jmMedicamento.add(jmiViaAdministracion);

        jmiFabricante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmiFabricante.setText("Fabricante");
        jmMedicamento.add(jmiFabricante);

        jmIngreso.add(jmMedicamento);

        jmbMenu.add(jmIngreso);

        jmReporte.setText("Reporte");
        jmReporte.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jmbMenu.add(jmReporte);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiIngresoActionPerformed

    private void jmiEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiEgresoActionPerformed

    private void jmiProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiProveedorActionPerformed

    private void jmiMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMedicamentoActionPerformed

    private void jmiEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiEnfermedadActionPerformed

    private void jmiCondicionAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCondicionAlmacenamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCondicionAlmacenamientoActionPerformed

    private void jmiFormaFarmaceuticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaFarmaceuticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiFormaFarmaceuticaActionPerformed

    private void jmiViaAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViaAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiViaAdministracionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmIngreso;
    private javax.swing.JMenu jmInventario;
    private javax.swing.JMenu jmMedicamento;
    private javax.swing.JMenu jmReporte;
    private javax.swing.JMenuBar jmbMenu;
    public javax.swing.JMenuItem jmiAcercaDe;
    public javax.swing.JMenuItem jmiCondicionAlmacenamiento;
    public javax.swing.JMenuItem jmiEgreso;
    public javax.swing.JMenuItem jmiEnfermedad;
    public javax.swing.JMenuItem jmiFabricante;
    public javax.swing.JMenuItem jmiFormaFarmaceutica;
    public javax.swing.JMenuItem jmiIngreso;
    public javax.swing.JMenuItem jmiMedicamento;
    public javax.swing.JMenuItem jmiProveedor;
    public javax.swing.JMenuItem jmiReceta;
    public javax.swing.JMenuItem jmiSalir;
    public javax.swing.JMenuItem jmiViaAdministracion;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
